language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: "pip install -r requirements.txt"
before_script:
  - chmod +x manage.py
script:
- python manage.py test